name: CI/CD

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [php, proxy, static]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.3.0

      - name: Cache Docker layers
        uses: actions/cache@v2.1.5
        with:
          path: /tmp/.buildx-cache
          key: docker-buildx-${{ matrix.version }}-${{ github.sha }}
          restore-keys: docker-buildx-${{ matrix.version }}-

      - name: Build
        run: |
          docker buildx build \
            --cache-from type=local,src=/tmp/.buildx-cache/${{ matrix.version }} \
            --cache-to type=local,dest=/tmp/.buildx-cache/${{ matrix.version }} \
            --output type=docker \
            --tag kooldev/nginx:${{ matrix.version }} \
            ${{ matrix.version }}

      - name: Tests
        run: docker run kooldev/nginx:${{ matrix.version }} nginx -v

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/master' && github.repository == 'kool-dev/nginx'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        if: github.ref == 'refs/heads/master' && github.repository == 'kool-dev/nginx'
        run: docker push kooldev/nginx:${{ matrix.version }}
